source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'TableCellPicker_Example', :exclusive => true do
  pod "TableCellPicker", :path => "../"
end

target 'TableCellPicker_Tests', :exclusive => true do
  pod "TableCellPicker", :path => "../"

  
end
